# Generated by Django 5.1.3 on 2025-04-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articulos",
            fields=[
                ("id_articulo", models.AutoField(primary_key=True, serialize=False)),
                ("titulo_articulo", models.CharField(max_length=255)),
                ("descripcion_articulo", models.TextField()),
                (
                    "institucion_articulo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "precio_articulo",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "db_table": "articulos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Calificaciones",
            fields=[
                (
                    "id_calificacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "tipo_calificacion",
                    models.CharField(
                        choices=[
                            ("excelente", "Excelente"),
                            ("buena", "Buena"),
                            ("mala", "Mala"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comentario", models.TextField()),
            ],
            options={
                "db_table": "calificaciones",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Categorias",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre_categoria",
                    models.CharField(
                        choices=[
                            ("prenda", "Prenda"),
                            ("utiles", "Utiles"),
                            ("libros", "Libros"),
                            ("herramientas", "Herramientas"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "categorias",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DetalleTransaccion",
            fields=[
                (
                    "id_detalle_transaccion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "tipo_transaccion",
                    models.CharField(
                        choices=[("venta", "Venta"), ("compra", "Compra")],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_entrega",
                    models.CharField(
                        choices=[
                            ("domicilio", "Domicilio"),
                            ("retiro_punto_fisico", "Retiro_Punto_Fisico"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad_articulos", models.IntegerField()),
            ],
            options={
                "db_table": "detalle_transaccion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pagos",
            fields=[
                ("id_pago", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_pago", models.DateTimeField(auto_now_add=True)),
                ("valor_pago", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[("aprobado", "Aprobado"), ("pendiente", "Pendiente")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "pagos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pqrs",
            fields=[
                ("id_pqr", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_pqr",
                    models.CharField(
                        choices=[
                            ("peticion", "Peticion"),
                            ("queja", "Queja"),
                            ("reclamo", "Reclamo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion_pqr", models.TextField()),
                ("fecha_pqr", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pqrs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("id_rol", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_rol",
                    models.CharField(
                        choices=[("vendedor", "Vendedor"), ("comprador", "Comprador")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "roles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Transacciones",
            fields=[
                ("id_transaccion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_transaccion", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "transacciones",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UsuarioRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "usuario_rol",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombres_usuario", models.CharField(max_length=255)),
                ("apellidos_usuario", models.CharField(max_length=255)),
                ("email_usuario", models.EmailField(max_length=254, unique=True)),
                ("contraseña_usuario", models.CharField(max_length=255)),
                ("fecha_registro", models.DateField(auto_now_add=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("telefono_usuario", models.CharField(max_length=20)),
                ("direccion_usuario", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "usuarios",
                "managed": False,
            },
        ),
    ]
