# Generated by Django 5.0.6 on 2025-09-12 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorias",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre_categoria",
                    models.CharField(
                        choices=[
                            ("prenda", "Prenda"),
                            ("utiles", "Útiles"),
                            ("libros", "Libros"),
                            ("herramientas", "Herramientas"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "categorias",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DetalleTransaccion",
            fields=[
                (
                    "id_detalle_transaccion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "tipo_transaccion",
                    models.CharField(
                        choices=[("venta", "Venta"), ("compra", "Compra")],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_entrega",
                    models.CharField(
                        choices=[
                            ("domicilio", "Domicilio"),
                            ("retiro_punto_fisico", "Retiro Punto Físico"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad_articulos", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "detalle_transaccion",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("id_rol", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_rol",
                    models.CharField(
                        choices=[("vendedor", "Vendedor"), ("comprador", "Comprador")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "roles",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Transacciones",
            fields=[
                ("id_transaccion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_transaccion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "transacciones",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombres_usuario", models.CharField(max_length=255)),
                ("apellidos_usuario", models.CharField(max_length=255)),
                ("email_usuario", models.EmailField(max_length=254, unique=True)),
                ("password_usuario", models.CharField(max_length=255)),
                ("fecha_registro", models.DateField(auto_now_add=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("telefono_usuario", models.CharField(max_length=20)),
                ("direccion_usuario", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True, null=True)),
            ],
            options={
                "db_table": "usuarios",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Articulos",
            fields=[
                ("id_articulo", models.AutoField(primary_key=True, serialize=False)),
                ("titulo_articulo", models.CharField(max_length=255)),
                ("descripcion_articulo", models.TextField()),
                (
                    "institucion_articulo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "precio_articulo",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="articulos/"),
                ),
                ("disponible", models.BooleanField(default=True)),
                (
                    "id_categoria",
                    models.ForeignKey(
                        db_column="id_categoria",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="udeneyv1.categorias",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="udeneyv1.usuarios",
                    ),
                ),
            ],
            options={
                "db_table": "articulos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ArticuloDetalleTransaccion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.IntegerField()),
                (
                    "id_articulo",
                    models.ForeignKey(
                        db_column="id_articulo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="udeneyv1.articulos",
                    ),
                ),
                (
                    "id_detalle_transaccion",
                    models.ForeignKey(
                        db_column="id_detalle_transaccion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="udeneyv1.detalletransaccion",
                    ),
                ),
            ],
            options={
                "db_table": "articulo_detalle_transaccion",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Pagos",
            fields=[
                ("id_pago", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_pago", models.DateTimeField(auto_now_add=True)),
                ("valor_pago", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[("aprobado", "Aprobado"), ("pendiente", "Pendiente")],
                        max_length=20,
                    ),
                ),
                (
                    "id_detalle_transaccion",
                    models.ForeignKey(
                        db_column="id_detalle_transaccion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="udeneyv1.detalletransaccion",
                    ),
                ),
            ],
            options={
                "db_table": "pagos",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="detalletransaccion",
            name="id_transaccion",
            field=models.ForeignKey(
                db_column="id_transaccion",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="udeneyv1.transacciones",
            ),
        ),
        migrations.CreateModel(
            name="Calificaciones",
            fields=[
                (
                    "id_calificacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "tipo_calificacion",
                    models.CharField(
                        choices=[
                            ("excelente", "Excelente"),
                            ("buena", "Buena"),
                            ("mala", "Mala"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comentario", models.TextField(blank=True, null=True)),
                (
                    "id_transaccion",
                    models.ForeignKey(
                        db_column="id_transaccion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="udeneyv1.transacciones",
                    ),
                ),
            ],
            options={
                "db_table": "calificaciones",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="transacciones",
            name="usuario",
            field=models.ForeignKey(
                db_column="id_usuario",
                on_delete=django.db.models.deletion.CASCADE,
                to="udeneyv1.usuarios",
            ),
        ),
        migrations.CreateModel(
            name="Pqrs",
            fields=[
                ("id_pqr", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_pqr",
                    models.CharField(
                        choices=[
                            ("peticion", "Petición"),
                            ("queja", "Queja"),
                            ("reclamo", "Reclamo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion_pqr", models.TextField()),
                ("fecha_pqr", models.DateTimeField(auto_now_add=True)),
                (
                    "id_transaccion",
                    models.ForeignKey(
                        db_column="id_transaccion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="udeneyv1.transacciones",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="udeneyv1.usuarios",
                    ),
                ),
            ],
            options={
                "db_table": "pqrs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UsuarioRol",
            fields=[
                ("id_usuario_rol", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_rol",
                    models.CharField(
                        choices=[("vendedor", "Vendedor"), ("comprador", "Comprador")],
                        db_column="id_rol",
                        max_length=10,
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="udeneyv1.usuarios",
                    ),
                ),
            ],
            options={
                "db_table": "usuario_rol",
                "managed": True,
                "unique_together": {("id_usuario", "id_rol")},
            },
        ),
    ]
