# Generated by Django 5.1.3 on 2024-12-02 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_usuario', models.CharField(max_length=255)),
                ('apellidos_usuario', models.CharField(max_length=255)),
                ('email_usuario', models.EmailField(max_length=254, unique=True)),
                ('contraseña_usuario', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_articulo', models.CharField(max_length=255)),
                ('descripcion_articulo', models.TextField()),
                ('institucion_articulo', models.CharField(max_length=255)),
                ('precio_articulo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udeneyv1.categoria')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udeneyv1.usuario')),
            ],
        ),
    ]
