# Generated by Django 5.0.6 on 2025-09-17 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udeneyv1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pqrs",
            name="id_usuario",
        ),
        migrations.CreateModel(
            name="Reportes",
            fields=[
                ("id_reporte", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_contenido",
                    models.CharField(
                        choices=[
                            ("articulo", "Artículo"),
                            ("usuario", "Usuario"),
                            ("comentario", "Comentario"),
                        ],
                        max_length=20,
                    ),
                ),
                ("id_contenido", models.IntegerField()),
                ("titulo_reporte", models.CharField(max_length=200)),
                ("razon_reporte", models.TextField()),
                ("descripcion_adicional", models.TextField(blank=True, null=True)),
                (
                    "estado_reporte",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("revisando", "Revisando"),
                            ("resuelto", "Resuelto"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_reporte", models.DateTimeField(auto_now_add=True)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                ("notas_moderador", models.TextField(blank=True, null=True)),
                (
                    "reportado_por",
                    models.ForeignKey(
                        db_column="reportado_por",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_enviados",
                        to="udeneyv1.usuarios",
                    ),
                ),
                (
                    "resuelto_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="resuelto_por",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes_resueltos",
                        to="udeneyv1.usuarios",
                    ),
                ),
            ],
            options={
                "db_table": "reportes",
                "managed": True,
            },
        ),
    ]
