# Generated by Django 5.0.6 on 2025-09-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udeneyv1", "0002_remove_pqrs_id_usuario_reportes"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarios",
            name="email_verified",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="verification_token",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="usuarios",
            name="verification_token_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
