# Generated by Django 5.0.6 on 2025-09-22 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udeneyv1", "0003_add_email_verification_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Eduney Marketplace", max_length=255),
                ),
                (
                    "site_description",
                    models.TextField(default="Plataforma de comercio electrónico"),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("registration_enabled", models.BooleanField(default=True)),
                ("password_min_length", models.IntegerField(default=8)),
                ("session_timeout", models.IntegerField(default=30)),
                ("max_login_attempts", models.IntegerField(default=5)),
                ("two_factor_auth", models.BooleanField(default=False)),
                ("email_notifications", models.BooleanField(default=True)),
                ("welcome_emails", models.BooleanField(default=True)),
                ("order_notifications", models.BooleanField(default=True)),
                (
                    "smtp_host",
                    models.CharField(default="smtp.gmail.com", max_length=255),
                ),
                ("smtp_port", models.IntegerField(default=587)),
                (
                    "smtp_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "smtp_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_gateway",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("mercadopago", "MercadoPago"),
                        ],
                        default="stripe",
                        max_length=20,
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(decimal_places=2, default=10000, max_digits=10),
                ),
                (
                    "max_order_amount",
                    models.DecimalField(
                        decimal_places=2, default=5000000, max_digits=10
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=19.0, max_digits=5),
                ),
                ("cache_enabled", models.BooleanField(default=True)),
                ("debug_mode", models.BooleanField(default=False)),
                (
                    "logging_level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "backup_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Diario"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_updates",
                        to="udeneyv1.usuarios",
                    ),
                ),
            ],
            options={
                "db_table": "system_config",
                "managed": True,
            },
        ),
    ]
