name: Ejecutar linters

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Ejecutar ESLint y Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias de Node.js
        run: npm install

      - name: Ejecutar ESLint
        run: npm run lint:js

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias de Python
        run: pip install flake8

      - name: Ejecutar Flake8
        run: flake8 .
