name: CD - Deploy Udeney to Azure VM

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }} << 'EOF'
            sudo apt update
            sudo apt install -y docker-compose-plugin
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin develop
            docker compose down
            docker compose up --build -d
          EOF
